// data/mdas.ts
export const mdasList = [
  { name: "Bank of Industry", abbreviation: "BOI" },
  { name: "Bureau for Public Procurement", abbreviation: "BPP" },
  { name: "Central Bank of Nigeria – National Collateral Agency", abbreviation: "CBN - NCR" },
  { name: "Commercial Law & Trademarks Registry", abbreviation: "CLTR" },
  { name: "Corporate Affairs Commission", abbreviation: "CAC" },
  { name: "Department of State Services", abbreviation: "DSS" },
  { name: "EFCC - Special Control Unit for Money Laundering", abbreviation: "SCUML" },
  { name: "Environmental Health Council of Nigeria", abbreviation: "EHCON" },
  { name: "Federal Airports Authority of Nigeria", abbreviation: "FAAN" },
  { name: "Federal Competition and Consumer Protection Commission", abbreviation: "FCCPC" },
  { name: "Federal Inland Revenue Service", abbreviation: "FIRS" },
  { name: "Federal Ministry of Aviation", abbreviation: "FMA" },
  { name: "Federal Ministry of Environment", abbreviation: "FME" },
  { name: "Federal Ministry of Finance", abbreviation: "FMF" },
  { name: "Federal Ministry of Foreign Affairs", abbreviation: "FMoFA" },
  { name: "Federal Ministry of Information and Culture", abbreviation: "FMIC" },
  { name: "Federal Ministry of Interior", abbreviation: "FMI" },
  { name: "Federal Ministry of Justice", abbreviation: "FMOJ" },
  { name: "Federal Ministry of Power", abbreviation: "FMP" },
  { name: "Federal Ministry of Transportation", abbreviation: "FMoT" },
  { name: "Federal Ministry of Works", abbreviation: "FMW" },
  { name: "Federal Produce Inspection Service", abbreviation: "FPIS" },
  { name: "Federal Road Safety Corps", abbreviation: "FRSC" },
  { name: "Galaxy Backbone Limited", abbreviation: "GBB" },
  { name: "Industrial Training Fund", abbreviation: "ITF" },
  { name: "Joint Tax Board", abbreviation: "JTB" },
  { name: "Ministry of Budget and National Planning", abbreviation: "BNP" },
  { name: "National Agency for Food and Drug Administration and Control", abbreviation: "NAFDAC" },
  { name: "National Drug Law Enforcement Agency", abbreviation: "NDLEA" },
  { name: "National Environmental Standards and Regulations Enforcement Agency", abbreviation: "NESREA" },
  { name: "National Identity Management Commission", abbreviation: "NIMC" },
  { name: "National Information Technology Development Agency", abbreviation: "NITDA" },
  { name: "National Inland Waterways Authority", abbreviation: "NIWA" },
  { name: "National Insurance Commission", abbreviation: "NAICOM" },
  { name: "National Office for Technology Acquisition and Promotion", abbreviation: "NOTAP" },
  { name: "National Pension Commission", abbreviation: "PENCOM" },
  { name: "National Bureau of Statistics", abbreviation: "NBS" },
  { name: "Nigeria Agricultural Quarantine Service", abbreviation: "NAQS" },
  { name: "Nigeria Broadcasting Commission", abbreviation: "NBC" },
  { name: "Nigeria Customs Service", abbreviation: "NCS" },
  { name: "Nigeria Export Processing Zone Authority", abbreviation: "NEPZA" },
  { name: "Nigeria Export Promotion Council", abbreviation: "NEPC" },
  { name: "Nigeria Gas Company", abbreviation: "NGC" },
  { name: "Nigeria Immigration Service", abbreviation: "NIS" },
  { name: "Nigeria Police Force", abbreviation: "NPF" },
  { name: "Nigerian Agricultural Insurance Corporation", abbreviation: "NAIC" },
  { name: "Nigerian Airspace Management Agency", abbreviation: "NAMA" },
  { name: "Nigeria Civil Aviation Authority", abbreviation: "NCAA" },
  { name: "Nigerian Communications Commission", abbreviation: "NCC" },
  { name: "Nigerian Content Development Management Board", abbreviation: "NCDMB" },
  { name: "Nigerian Copyright Commission", abbreviation: "NCC" },
  { name: "Nigerian Electricity Management Service Agency", abbreviation: "NEMSA" },
  { name: "Nigerian Electricity Regulatory Commission", abbreviation: "NERC" },
  { name: "Nigerian Export-Import Bank", abbreviation: "NEXIM" },
  { name: "Nigerian Investment Promotion Commission", abbreviation: "NIPC" },
  { name: "Nigerian Maritime Administration and Safety Agency", abbreviation: "NIMASA" },
  { name: "Nigerian Midstream and Downstream Petroleum Regulatory Authority", abbreviation: "NMDPRA" },
  { name: "Nigerian Ports Authority", abbreviation: "NPA" },
  { name: "Nigerian Postal Service", abbreviation: "NIPOST" },
  { name: "Nigerian Shippers’ Council", abbreviation: "NSC" },
  { name: "Nigerian Upstream Petroleum Regulatory Commission", abbreviation: "NUPRC" },
  { name: "Office of the Head of the Civil Service of the Federation", abbreviation: "OHCSF" },
  { name: "Oil & Gas Free Zone Authority", abbreviation: "OGFZA" },
  { name: "Patent and Design Registry", abbreviation: "PDR" },
  { name: "Presidential Task Force on Money Laundering", abbreviation: "PTFML" },
  { name: "Office of the Secretary to the Government of the Federation", abbreviation: "OSGF" },
  { name: "Securities and Exchange Commission", abbreviation: "SEC" },
  { name: "Service Compact", abbreviation: "SERVICOM" },
  { name: "Standards Organisation of Nigeria", abbreviation: "SON" },
];

