import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";

interface StateRankingRow {
  state: string;
  rank: number;
  totalScore: number;
  maxScore: number;
  percentageScore: number;
}

interface GenerateStateRankingPDFParams {
  rankings: StateRankingRow[];
  indicatorLabel: string;
  indicatorKey?: string;
  generatedAt?: Date;
}

export async function generateStateRankingPDF({
  rankings,
  indicatorLabel,
  indicatorKey,
  generatedAt = new Date(),
}: GenerateStateRankingPDFParams): Promise<void> {
  if (!rankings || rankings.length === 0) {
    toast.error("No ranking data available to download");
    return;
  }

  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 30;

    // Attempt to add logo for consistent branding
    try {
      const logoUrl = "/images/logo/logo_pebec1.PNG";
      const img = new Image();
      img.src = logoUrl;
      img.crossOrigin = "anonymous";
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
        setTimeout(() => reject(new Error("Logo load timeout")), 5000);
      });

      const logoWidth = 60;
      const logoHeight = 18;
      const logoX = (pageWidth - logoWidth) / 2;
      doc.addImage(img, "PNG", logoX, 10, logoWidth, logoHeight);
      yPosition = 40;
    } catch (error) {
      console.error("Error loading logo:", error);
      doc.setFontSize(16);
      doc.setFont(undefined, "bold");
      doc.text("PEBEC", pageWidth / 2, 20, { align: "center" });
      yPosition = 35;
    }

    // Title and metadata
    doc.setFontSize(18);
    doc.setFont(undefined, "bold");
    doc.text(`State Rankings - ${indicatorLabel}`, pageWidth / 2, yPosition, {
      align: "center",
    });
    yPosition += 8;

    doc.setFontSize(12);
    doc.setFont(undefined, "normal");
    doc.text(
      `Generated: ${generatedAt.toLocaleDateString(undefined, {
        year: "numeric",
        month: "short",
        day: "numeric",
      })}`,
      pageWidth / 2,
      yPosition,
      { align: "center" }
    );
    yPosition += 5;

    if (indicatorKey) {
      doc.setFontSize(10);
      doc.text(`Indicator Key: ${indicatorKey}`, pageWidth / 2, yPosition, {
        align: "center",
      });
      yPosition += 5;
    }

    yPosition += 8;

    const tableData = rankings.map((row) => [
      `#${row.rank}`,
      row.state,
      `${row.totalScore.toFixed(1)}/${row.maxScore.toFixed(1)}`,
      `${row.percentageScore.toFixed(1)}%`,
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [["Rank", "State", "Score", "% Score"]],
      body: tableData,
      headStyles: {
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      bodyStyles: { fontSize: 10 },
      styles: { fontSize: 10 },
      theme: "striped",
      margin: { left: 10, right: 10 },
      didDrawPage: (data) => {
        doc.setFontSize(9);
        doc.text(
          `Generated by PEBEC Ranking System`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
        doc.text(
          `Page ${data.pageNumber}`,
          pageWidth - 20,
          pageHeight - 10,
          { align: "right" }
        );
      },
    });

    const indicatorSegment = indicatorKey ? indicatorKey : "all";
    const isoDate = generatedAt.toISOString().split("T")[0];
    const fileName = `state-ranking-${indicatorSegment}-${isoDate}.pdf`;
    doc.save(fileName);
    toast.success("PDF downloaded successfully!");
  } catch (error) {
    console.error("Error generating State Ranking PDF:", error);
    toast.error("Failed to download State Ranking PDF");
  }
}


