const reformsData = [
    {
      letter: "A",
      name: "Business Registration Process",
      reforms: [
        "Introduction of an online business registration portal",
        "Upgrade and full automation of unique name reservation.",
        "The reservation of unique company names is now completed within a few hours, compared to the previous 12-hour timeframe.",
        "Simplified company incorporation (CAC 1.1).",
        "Elimination of the need for a lawyer to register a business.",
        "Introduction of a single form for business registration.",
        "Introduction of a digital signature system for business registration.",
        "Reduction of the time for registering a foreign-owned business.",
        "Introduction of a pre-incorporation checklist for new businesses.",
        "Elimination of the need for physical stamping of documents.",
        "Signing the declaration of compliance by a staff of the CAC who are lawyers.",
        "Registration of a company at the Corporate Affairs Commission (CAC) through the Company Registration Portal (CRP) within 24 hours from the document upload.",
        "Payment of registration fees through the online Company Registration Portal (CRP).",
        "Registration of companies by general purpose clause on the Company Registration Portal (CRP).",
        "Elimination of requirement for a company seal for business registration.",
        "Elimination of procedure for procuring company seal.",
        "Automatic generation of Tax Identification Number (TIN) by the Federal Inland Revenue Service (FIRS) upon completion of registration.",
        "Non-requirement of physical inspection of business premises in Kano State.",
        "Pay registration fee for business premises into a government account at a designated bank.",
        "Automation of process for obtaining a business premises permit.",
        "Inclusion on the Company Registration Portal of the payment of stamp duties payable to the Federal Inland Revenue Service.",
        "Insertion of Tax Identification Number (TIN) on the Certificates of Company Registration by the Corporate Affairs Commission.",
        "Elimination of the procedure requiring the mandatory use of declaration of compliance.",
        "Reduction in the cost of registration payable to the Corporate Affairs Commission (CAC) from N15,000 to N10,000.",
        "Reduction of the time for filing annual returns.",
      ],
    },
    {
      letter: "B",
      name: "Dealing with Construction Permits",
      reforms: [
        "Elimination of the need for multiple inspections during construction.",
        "Introduction of an online platform for building plan approvals.",
        "Elimination of impact assessment for the building of 2-floor storage warehouse.",
        "Simultaneously making submissions of application and payment for building plan.",
        "Publication of fees, procedures and laws on the Lagos State Physical Planning and Permit Authority (LASPPPA) website (www.lagosepp.com.ng).",
        "Limitation of soil test and environmental impact assessment (EIA) to only specialised cases and eliminating the need to obtain a soil investigation report.",
        "Elimination of the requirement of obtaining a certified true copy (CTC) of title document and a CTC of the survey plan.",
        "Availability of statistical information on land disputes.",
        "Removal of infrastructure development charge for 2-floor warehouses.",
        "Enablement of access to water connection in 3 days.",
        "Elimination of infrastructure development charge (IDC) for warehouses in Lagos.",
        "Submission of application and payment for building plan are done simultaneously.",
        "Introduction of e-payment at the Kano Urban Planning and Development Authority (KNUPDA).",
        "Integrating application for building plan with payment in Kano (procedure reduction).",
        "Cost reduction considerations for less risky and small projects.",
        "Building plan now obtainable within 14 days.",
        "Private professional firms are appointed to carry out inspection before, during and after construction.",
        "Elimination of physical inspection preceding issuance of certificate of habitation.",
        "Receiving of water connection in 7 days instead of 30 days, and making it now simultaneous with payment.",
        "Operationalisation of e-planning platform for Lagos to optimise the planning permit process.",
      ],
    },
    {
      letter: "C",
      name: "Getting Electricity",
      reforms: [
        "Reduction in time to obtain an Environmental Impact Assessment (EIA) report.",
        "Elimination of the need for multiple inspections before electricity connections.",
        "Reduction of procedures for new connections to the distribution grid.",
        "Reduction of timeline for new connections to the distribution grid.",
        "Introduction of e-system for application and approval for new connections to the grid.",
        "Statutory requirement to meter Maximum Demand customers prior to connection.",
        "Introduction of advance customer notification for prolonged outages.",
        "Introduction of notice-based e-system for works that involve crossing of road (right-of-way).",
        "Introduction of e-system for application submission and approval for getting electricity.",
        "DISCOs to implement grid mapping, using technology (GIS or EMS/SCADA).",
        "Encourage adherence to timeline for Environmental Impact Assessment (EIA) application process.",
        "Drive 100% compliance with the NERC Order on timelines for new connections to the grid.",
      ],
    },


    {
        letter: "D",
        name: "Registering Property",
        reforms: [
          "Availability of independent land dispute resolution body.",
          "Applicants can now obtain CTC of title document at a Land registry automated centre.",
          "Demand notice for registration fees, consent fees and neighbourhood improvement charge can now be obtained via email.",
          "Make online payment for charting fee, endorsement fee, stamp duty, registration fees, consent fees and neighbourhood improvement charges.",
          "Stamping of deed of assignment is now done internally in the stamp duty office within the Lands Bureau.",
          "Single filing database for Lands Bureau and cadastral mapping.",
          "Availability of cadastral Information, Boundaries, Plan and Digital Mapping Products.",
          "Publication of statistical information on land disputes and the availability of list of properties with pending court cases.",
          "Information on fees, procedures, and access to the Geographical Information System (GIS) is now available on the lands bureau website.",
          "The payment of charting fees, endorsement fees, and Form 1C fees has now been consolidated with the payment of stamp duty, registration fees, consent fees, capital gains tax (CGT), and the neighbourhood improvement charge.",
          "National identity database for accuracy of identity documents.",
          "Automation of the registration of properties at the Land Registry.",
          "Expedition of the issuance of Governor's consent through delegation of issuance authority to the State Attorney-General and Commissioner for Justice.",
          "Availability of rapid capture at the Land Registry.",
          "The Land Registry website is now linked to the Inland Revenue Portal and all required payments can be made online simultaneously.",
          "Digitisation of Land Registry and the systematic land title registration for harmonised title and boundary verification in the Land Registry.",
          "Availability of a defined fee schedule for registering.",
          "Cadastral mapping of the economy.",
          "The Kano Bureau for Land Management website has been enriched with vital information required for acquisition and transfer of property.",
          "Update information on land disputes.",
        ],
      },
      {
        letter: "E",
        name: "Getting Credit",
        reforms: [
          "Creation of a National Collateral Registry by the Central Bank of Nigeria (CBN) with the support of the International Finance Corporation (IFC).",
          "Passage of Credit Bureau Services Bill.",
          "Passage of the Secured Transactions in Movable Assets (aka Collateral Registry) Bill.",
          "Right of law to access their credit reports.",
          "Usage of credit history and credit scoring.",
          "Borrowers have the right of law to access their credit report data.",
          "Credit reports are now a value-added service for all concerned.",
          "Secured Creditors are paid First when a Business is Liquidated.",
          "Secured creditors are subject to an automatic stay on enforcement when a debtor enters a court-supervised reorganization process. This law safeguards secured creditors' rights by establishing clear grounds for relief from the stay and imposing a six-month time limit."
        ],
      },

      {
        letter: "F",
        name: "Protecting Minority Investors",
        reforms: [
          "Directors with a direct or indirect interest in a current or proposed company transaction must promptly disclose it in writing to the board, specifying the details of their interest.",
          "A shareholder may file a personal action to enforce their individual rights or a representative action on behalf of themselves and other affected members to uphold their collective rights.",
          "Plaintiffs can now request the court to compel defendants and witnesses to produce any relevant documents during a civil trial.",
          "Shareholder approval is now required for the sale of assets exceeding 50% of the company’s total asset value.",
          "Shareholders have automatic pre-emptive rights on new shares, requiring the company to first offer newly issued shares to existing shareholders of the same class in proportion to their current holdings.",
          "Public companies, both listed and unlisted, are now prohibited from appointing the same person as chairman and chief executive officer.",
          "Public companies, both listed and unlisted, must have at least three independent directors on their board.",
          "Companies must disclose individual managers' remuneration at the annual general meeting."
        ],
      },

      {
        letter: "G",
        name: "Paying Taxes",
        reforms: [
          "Introduction of e-Filing of Federal Taxes.",
          "Centralisation of electronic payment of all Federal Taxes to allow users pay their taxes online.",
          "Full disclosure on tax audit guidelines in Nigeria.",
          "Rollout of electronic self-service help desks at all FIRS offices.",
          "Defined timeline to complete a corporate income tax (CIT) audit.",
          "Driving of increased usage of the e-filing system.",
          "Filing of PAYE and Personal Income Taxes electronically in Lagos (filing).",
          "Filing of PAYE and Personal Income Taxes electronically in Kano (filing).",
          "Paying for PAYE and Personal Income Taxes electronically in Lagos (paying).",
          "Paying for PAYE and Personal Income Taxes electronically in Kano (paying).",
          "Automation of the process for Registration for Personal Income Tax by Lagos Internal Revenue Service.",
          "Creation of a simplified single schedule for each tax type on the e-filing platform.",
          "Introduction of a pre-approval checklist for tax filings.",
          "Elimination of the need for multiple payments for tax filings.",
          "Introduction of a digital tax clearance certificate system."
        ],
      },
      {
        letter: "H",
        name: "Trading Across Borders",
        reforms: [
          "Implementation of 24/7 operations of Apapa port.",
          "Implementation of single joint cargo inspection.",
          "Elimination of hard copies of shipping documents.",
          "Digitisation of export document; Request for Information (RFI).",
          "Reduction of documentation for export from ten (10) to seven (7) documents and reduction of documentation for import from fourteen (14) to eight (8).",
          "Automation of scheduling process by pre-shipment Agents.",
          "Introduction of sanctions for non-compliance by pre-shipment agents.",
          "Implementation of interactive website by Pre-Shipment Inspection Agents (PIAs).",
          "PIAs’ compliance with 24hrs issuance of Clean Certificate of Inspection (CCI) and 48hrs inspection of export.",
          "Announced timelines for issuance of SONCAP certificates and time limits for completing inspections at origin.",
          "Enforced compliance of timelines for approval of Form Ms by banks.",
          "Processing of Net Export Proceeds Form to be completed within 24 hours.",
          "Nigeria Customs Service to take lead role in coordinating and scheduling the enforced joint examination of import cargo.",
          "Advance Risk Manifest to be transmitted to Terminal Operators so as to optimise cargo placement.",
          "Enforce mandatory transmission of shipping line manifest to NPA and NCS, maximum 7 days before arrival of vessel to Nigeria.",
          "Introduction of a pre-approval checklist for import/export applications.",
          "Elimination of the need for multiple payments for import/export applications.",
          "Introduction of a digital customs clearance certificate system."
        ],
      },
      {
        letter: "I",
        name: "Enforcing Contracts",
        reforms: [
          "Publication of Court of Appeal judgments.",
          "Set-up of specialised small claims commercial courts in 32 States and the FCT.",
          "Limitation on adjournments incorporated in the specialised small claims commercial courts in 32 States and the FCT.",
          "Introduction of pre-trial conference for specialised small claims commercial courts in 32 States and the FCT.",
          "Time reduction in dispute resolution between trial and judgment.",
          "Time reduction for execution of judgments.",
          "Publication of performance reports online on an accessible website.",
          "Time reduction for filing and service.",
          "Communication between parties in dispute via electronic means.",
          "Introduction of a single fee structure for the filing of court cases.",
          "Introduction of self-representation at the Small Claims Court."
        ],
      },
        {
          letter: "J",
          name: "Resolving Insolvency",
          reforms: [
            "Introduction of administration and company voluntary arrangements (re-organisation options) for financially distressed companies.",
            "Allow creditors file for insolvency of the debtor through administration.",
            "Invalidation of undervalued transactions.",
            "Obtaining post-commencement credit to finance.",
            "Provision for continuation of contracts supplying essential goods and services to the debtor.",
            "Dissenting creditors in re-organisation receive as much as what they would obtain in liquidation.",
            "Recognise voting rights of creditors on reorganisation plans.",
            "Ensure that creditors can be divided into classes and each class may vote separately to vote on the re-organisation plan.",
            "Participation of creditors in the selection and approval of the Insolvency Practitioner.",
            "Approval by creditors for sale of substantial assets of debtor.",
            "Reduction in the cost of filing insolvency applications.",
            "Streamlining the documents required for insolvency judgements.",
            "Reduction of the time for enforcing insolvency judgments."
          ],
        },
        {
          letter: "K",
          name: "Trading Within Nigeria",
          reforms: [
            "Enforcement of processing timeline for registration of food (90 days) and drugs (120 days) in Nigeria.",
            "Introduction of the online registration process for food and drugs.",
            "Automation of port operation processes.",
            "Clearance of all pending registration applications as of December 2017.",
            "Availability and clarity of defined fees, documentation, and processes for registering a product with NAFDAC online.",
            "Review and publication of Product Renewal Process online.",
            "Reduce interception of containers by SON officials after release at ports.",
            "Issuance of all outstanding clearance of opposition by Trademarks Registry.",
            "Issuance of all outstanding clearance of registration by Trademarks Registry.",
            "Publishing of a backlog of all e-applications in the Trademark Journal (30,000 outstanding marks).",
            "Existing NOTAP guidelines reviewed based on feedback/input from the consultative sessions held with stakeholders.",
            "Publication of all processes, documentation, and timelines to the registration of Technology Transfer Agreements on the NOTAP website.",
            "Streamlining of the application form and supporting documentation to the registration of Technology Transfer Agreements.",
            "Launch E-MANCAP across all major cities in Nigeria.",
            "Clarity on NAFDAC processes and fees."
          ],
        },
        {
          letter: "L",
          name: "Easy Entry and Exit of People",
          reforms: [
            "Elimination of Passenger Service Charge (PSC) Stickers.",
            "Simplification of visa-on-arrival process.",
            "48-hr visa processing timeline across missions abroad.",
            "Reduction of the infrastructural deficits at the Nigerian Airports.",
            "Institution of fines for airlines for non-compliance with passengers' rights.",
            "Update of NIS website to clarify end-to-end visa and permits instructions.",
            "Harmonisation of multiple departure and arrival forms at the airports.",
            "Mandating of 48-hour visa processing time for tourist and business visa at NIS and the Nigerian Missions Abroad.",
            "Mandating of 48-hour visa processing time for VOA preapproval.",
            "Infrastructural improvements (Abuja airport).",
            "Infrastructural improvements (Lagos airport).",
            "Elimination of manual baggage searches.",
            "Implementation of Single Passenger Clearance System at airports.",
            "Processing and approval of Temporary Work Permit (TWP) within 48 hours.",
            "Deployment of PEBEC feedback kiosks at Lagos & Abuja airports.",
            "Upgrade of the FAAN website to reflect approved airport procedures.",
            "Automated Expatriate Quota (EQ) application process at the Federal Ministry of Interior (FMI).",
            "New Immigration Regulation 2017. The Ministry of Interior has approved and launched a new Immigration Regulation."
          ],
        },
      
                        
  ];
  
  export default reformsData;
  